---
--- Generated by Luanalysis
--- Created by tisudd22zaczel.
--- DateTime: 2023-04-20 20:05
---

local RequestTypes = {}
local DataTypes = {}

local ws, error = http.websocket("ws://localhost:8081")

local x, y, z = gps.locate();

local items = {}

for i = 1, #arg, 2 do
    local amount = tonumber(arg[i+1])
    if amount and type(arg[i]) == "string" then
        table.insert(items, {id = arg[i], amount = amount})
    end
end

print("requesting: ")
local objArray = {}
for i, item in pairs(items) do
    print(item.id .. " " .. item.amount)
end

ws.send(textutils.serialiseJSON({type = DataTypes.request, pos = {x = x, y = y, z = z}, items = items, id = os.getComputerID()}));